#!/usr/bin/env python

import numpy as np
import matplotlib.pyplot as plt
import fileinput
import sys


data = np.array([float(line) for line in fileinput.input(sys.argv[2:])])
plt.hist(data, bins=60)
plt.show()
