#!/usr/bin/env python
import json
import sys
import os

def main(args):
    if len(args) != 2:
        return 2

    file, key = args

    try:
        with open(file, "r") as f:
            data = json.load(f)
    except e:
        return str(e)

    if key not in data:
        return f"Key {key} is not a toplevel key of json file at {file}"

    if not isinstance(data, dict):
        return "JSON is not object"

    return str(data[key])

if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
