#!/usr/bin/env python

import sys
from _.image_pil import tight_crop
from PIL import Image


def run(file):
    smol_img = tight_crop(Image.open(file))
    w, h = smol_img.size
    print(f"{w} {h}")


def main(args):
    if len(args) > 0 and args[0] != "-":
        for file in args:
            run(file)
    else:
        for file in sys.stdin.read().split():
            run(file)


sys.exit(main(sys.argv[1:]))
